---
  - name: "Добавление ключа репозитория clickhouse"
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: E0C56BD4
      state: present

  - name: "Добавления репозитория clickhouse"
    apt_repository:
      repo: deb http://repo.yandex.ru/clickhouse/deb/stable/ main/
      state: present
      filename: clickhouse

  - name: "Установка клиента и сервера clickhouse"
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - clickhouse-client
      - clickhouse-server

  - name: "Развертывание конфигурации clickhouse"
    template:
      src: config.xml
      dest: /etc/clickhouse-server/config.xml
    notify:
      - "Запуск clickhouse-server"